version: 2.1

orbs:
  python: circleci/python@1.2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.4

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test:
          context: deg-testing
      - deploy:
          context: aws-data-shared-services
          filters:
            branches:
              only:
                - master
                - main
          requires:
            - build-and-test

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install poetry
          command: |
            make install-poetry
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          # Pulls bonobos-singer-support from Github, which requires
          # using a machine user SSH key.  See
          # https://circleci.com/docs/2.0/gh-bb-integration/#controlling-access-via-a-machine-user
          name: Pull dependencies
          command: make deps
      - run:
          name: Run tests
          command: make ci
      - run:
          name: Check coverage
          command: make coverage-report
      - run:
          name: Lint
          command: make lint
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install s3pypi
          command: sudo pip install s3pypi
      - run:
          name: Release package
          command: |
            s3pypi --bucket deg-shared-services-pypi-us-east-1 --private --secret ${S3PYPI_SECRET}
